# DO NOT EDIT THIS FILE!

# Torrus SIAM plugin default configuration
# Put all your local settings into siam-siteconfig.pl

use lib(@perllibdirs@);

$Torrus::SIAM::version        = '@VERSION@';


# Default location for DDX files
$Torrus::SIAM::ddx_path = '@sitedir@/discovery/';

# Default location for DevDiscover bundle XML files
$Torrus::SIAM::bundles_path = '@sitexmldir@/bundles';

# Default location for DevDiscover per-node XML files
$Torrus::SIAM::nodes_path = '@sitexmldir@/nodes';

# Default location for RRD files
$Torrus::SIAM::rrd_path = '@defrrddir@';

# Default DDX parameters
$Torrus::SIAM::ddx_defaults = {
    'host-subtree'   => '/',
    'snmp-port'      => '161',
    'snmp-version'   => '2c',        
    'snmp-community' => 'public',
    'snmp-timeout'   => 3,
    'snmp-retries'   => 2,
    'CiscoIOS_cbQoS::classmaps-only' => 'yes',
};


@Torrus::SIAMDD::match_port_name_attributes =
    ('torrus.port.name',
     'torrus.port.shortname');

require '@siam_siteconfig_pl@';

1;
