# DO NOT EDIT THIS FILE!

# Torrus SIAM plugin default configuration
# Put all your local settings into siam-siteconfig.pl

use lib(@perllibdirs@);

$Torrus::SIAM::version        = '@VERSION@';


# Default location for DDX files
$Torrus::SIAM::ddx_path = '@sitedir@/discovery/';

# Default location for DevDiscover bundle XML files
$Torrus::SIAM::bundles_path = '@sitexmldir@/bundles';

# Default location for DevDiscover per-node XML files
$Torrus::SIAM::nodes_path = '@sitexmldir@/nodes';

# Default location for RRD files
$Torrus::SIAM::rrd_path = '@defrrddir@';

# Default DDX parameters
$Torrus::SIAM::ddx_defaults = {
    'host-subtree'   => '/',
    'snmp-port'      => '161',
    'snmp-version'   => '2c',        
    'snmp-community' => 'public',
    'snmp-timeout'   => 3,
    'snmp-retries'   => 2,
    'CiscoIOS_cbQoS::classmaps-only' => 'yes',
    'RFC2863_IF_MIB::list-admindown-interfaces' => 'yes',
    'SIAM::exclude-unmatched-admindown-interfaces' => 'yes',
};


# sets of device parameters triggered by torrus.device_template
# device attribute. The templates should be defined in siam-siteconfig.pl
%Torrus::SIAM::ddx_device_templates = ();


####  SNMP discovery integration

push(@Torrus::SIAMDD::loadModules,
     'Torrus::DevDiscover::SIAMDD::IFMIB',
     'Torrus::DevDiscover::SIAMDD::APC_PowerNet');


@Torrus::SIAMDD::match_port_name_attributes =
    ('siam.devc.name',
     'torrus.port.shortname');

@Torrus::SIAMDD::match_port_properties =
    ('ifName',
     'ifDescr',
     'ifAlias');

# parameters for automatic linking of SIAM::DeviceComponents
# to SIAM::ServiceComponents

# activiate automatic linking
$Torrus::SIAMDD::ifmib_search_svcc_in_description = 0;

# pattern to search for
$Torrus::SIAMDD::ifmib_search_svcc_pattern = '\{(\d+)\}';

# SIAM::ServiceComponent prefix (if needed)
$Torrus::SIAMDD::ifmib_search_svcc_prefix = 'SC';


require '@siam_siteconfig_pl@';

1;
